/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { VotingSystem__factory } from "./VotingSystem__factory";
export { VotingToken__factory } from "./VotingToken__factory";
